import styled from "@emotion/styled";

export const FlexContainer = styled.div`
  flex: ${(props) => props.flex};
  position: ${(props) => props.position};
  justify-content: ${(props) => props.justifyContent};
  align-items: ${(props) => props.alignItems};
  width: ${(props) => props.width};
  height: ${(props) => props.height};
  min-height: ${(props) => props.minHeight};
  min-width: ${(props) => props.minWidth};
  max-height: ${(props) => props.maxHeight};
  max-width: ${(props) => props.maxWidth};
  padding: ${(props) => props.padding};
  margin-right: ${(props) => props.marginRight};
  margin-bottom: ${(props) => props.marginBottom};
  margin: ${(props) => props.margin};
  flex-wrap: ${(props) => props.flexWrap};
  flex-direction: ${(props) => props.flexDirection};
  background-color: ${(props) => props.backgroundColor};
  background: ${(props) => props.background};
  color: ${(props) => props.textColor};
  top: ${(props) => props.top};
  right: ${(props) => props.right};
  bottom: ${(props) => props.bottom};
  left: ${(props) => props.left};
  z-index: ${(props) => props.zIndex};
  overflow: ${(props) => props.overflow};
  border-radius: ${(props) => props.borderRadius};
  border: ${(props) => props.border};
  box-shadow: ${(props) => props.boxShadow};
  visibility: ${(props) => props.visibilityProp};
  display: ${(props) => props.display || "flex"};
  cursor: ${(props) => props.cursor};
  gap: ${(props) => props.gap};
  padding-right: ${(props) => props.paddingRight};
  background-image: ${(props) => props.backgroundImage};
  background-size: cover;
  background-position: center;
  transform: ${(props) => props.transform};
`;
